name: build-deploy

on:
  push:
    branches:
      - master

jobs:

  #
  # can add a job to test Python (lint + pytest)

  build-yarn:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Yarn Installation
        run: |
          mkdir ~/.npm-global
          npm config set prefix '~/.npm-global'
          export PATH=~/.npm-global/bin:$PATH
          source ~/.profile
          npm install -g yarn
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        working-directory: ./www
        run: yarn install
      - name: Build
        working-directory: ./www
        run: yarn build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: www/dist

  #
  # No ssh port open, can't be used for now
  #deploy:
  #  name: Deploy
  #  needs: build
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Checkout Repo
  #      uses: actions/checkout@master
  #    - name: Download Artifact
  #      uses: actions/download-artifact@master
  #      with:
  #        name: build
  #        path: www/dist
  #    - name: deploy on webserver
  #      uses: horochx/deploy-via-scp@master
  #      with:
  #        local: www/dist
  #        remote: ${{ secrets.REMOTE }}
  #        host: ${{ secrets.HOST }}
  #        port: ${{ secrets.PORT }}
  #        user: ${{ secrets.USER }}
  #        key: ${{ secrets.KEY }}