name: build-deploy

on:
  push:
    branches:
      - master

jobs:

  #
  # can add a job to test Python (lint + pytest), need unit-test

  build-yarn:
    name: Build Yarn
    runs-on: ubuntu-latest
    steps:
      - name: Yarn Installation
        run: |
          mkdir ~/.npm-global
          npm config set prefix '~/.npm-global'
          export PATH=~/.npm-global/bin:$PATH
          source ~/.profile
          npm install -g yarn
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        working-directory: ./www
        run: yarn install
      - name: Build
        working-directory: ./www
        run: yarn build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: www/dist

  deploy-webserver:
    name: Deploying on webserver
    runs-on: ubuntu-latest
    needs: build-yarn
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Calling webhook
        uses: distributhor/workflow-webhook@v1
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
